---
title: "LLLTO_Viz"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(reticulate)
library(sf)
library(plotly)
library(feather)
library(ggridges)

knitr::opts_chunk$set(echo = TRUE)
```

## Baseline Comparisons

```{r}
# if you're using Rstudio:
setwd(dirname(rstudioapi::getSourceEditorContext()$path))
setwd('../../river-dl')
source('../drb_gwnet/2_Analysis/utils.R')

spatial <- readRDS('data_DRB/DRB_spatial/network.rds')
edges <- spatial$edges %>% st_as_sf()

metrics <- c('overall_metrics','month_metrics','reach_metrics')

gwn_stats <- metrics %>% map(~combine_replicates('results/baseline/GWN',.,subfolders=T))
names(gwn_stats) <- c('temps','months','segs')

rgcn_stats <- metrics %>% map(~combine_replicates('results/baseline/RGCN',.,subfolders = T))
names(rgcn_stats) <- c('temps','months','segs')

gwn_reps <- read_replicates('results/baseline/GWN/full_train', 'overall_metrics') %>% 
  filter(partition=='tst')## Best, 6
rgcn_reps <- read_replicates('results/baseline/RGCN/full_train', 'overall_metrics') %>%
  filter(partition=='tst')## Best, 2

### function for comparing across replicates
replicate_comps <- function(run1,run2, scenario){
  run_1 <- read_replicates(run1, 'overall_metrics')
  run_2 <- read_replicates(run2, 'overall_metrics')
  sig_test<-t.test(run_1$rmse[run_1$partition=='tst'],run_2$rmse[run_2$partition=='tst']) %>%
    broom::tidy() %>% mutate(group='overall') %>%
    bind_rows(t.test(run_1$rmse_top10[run_1$partition=='tst'],run_2$rmse_top10[run_2$partition=='tst']) %>%
      broom::tidy() %>% mutate(group='warmest10')) %>%
    mutate(scenario = scenario)
  return(sig_test)
}

replicate_sigs <- replicate_comps('results/baseline/GWN/full_train','results/baseline/RGCN/full_train', 'baseline') %>%
  bind_rows(replicate_comps('results/LLO/coastal/GWN/full_train','results/LLO/coastal/RGCN/full_train', 'coastal')) %>%
  bind_rows(replicate_comps('results/LLO/appalachians/GWN/full_train','results/LLO/appalachians/RGCN/full_train', 'appalachians')) %>%
  bind_rows(replicate_comps('results/LLO/piedmont/GWN/full_train','results/LLO/piedmont/RGCN/full_train', 'headwaters')) %>%
  bind_rows(replicate_comps('results/LTO/max/GWN/full_train','results/LTO/max/RGCN/full_train', 'train cold/test hot')) %>%
  bind_rows(replicate_comps('results/LTO/min/GWN/full_train','results/LTO/min/RGCN/full_train', 'train hot/test cold')) %>%
  bind_rows(replicate_comps('results/Drought/GWN/full_train','results/Drought/RGCN/full_train', 'Drought')) %>%
  mutate(best = ifelse(estimate1<estimate2, "GWN","RGCN"))

overall_sigs <- replicate_sigs %>% filter(group == 'overall',p.value < 0.05)
warmest_sigs <- replicate_sigs %>% filter(group == 'warmest10',p.value < 0.05)

shapiro.test(rgcn_reps$rmse[rgcn_reps$partition=='tst'])

check <- t.test(gwn_reps$rmse[gwn_reps$partition=='tst'],rgcn_reps$rmse[rgcn_reps$partition=='tst'])

t.test(gwn_reps$rmse_top10[gwn_reps$partition=='tst'],rgcn_reps$rmse_top10[rgcn_reps$partition=='tst'])

check <- t.test(rgcn_reps$rmse[rgcn_reps$partition=='tst']) %>% broom::tidy() %>%
  mutate(model = 'rgcn') %>%
  bind_rows(t.test(rgcn_reps$rmse[rgcn_reps$partition=='tst']) %>% broom::tidy() %>%
  mutate(model = 'gwn'))

ggplot(check, aes(x = model, y = estimate))+
  geom_point()+
  geom_errorbar(aes(ymin = conf.low, ymax= conf.high))
t.test(gwn_reps$rmse[gwn_reps$partition=='tst'],rgcn_reps$rmse[rgcn_reps$partition=='tst'], alternative='less')

## Figure for overall difference between the two models

p1 <- gwn_stats$segs %>% mutate(run = 'GraphWaveNet') %>% bind_rows(rgcn_stats$segs %>% mutate(run = 'RGCN')) %>%
  filter(train_type == "Full Train") %>%
  seg_plotter_sf(., 'rmse_mean') +
  facet_wrap(~run) + labs(color = 'RMSE\n(°C)', title = ' ') +
  theme(legend.title = element_text(size=8))

p1

baseline_diff <- seg_error_diff(rgcn_stats$segs, gwn_stats$segs, 'RGCN', 'GraphWaveNet',shape=edges)


###Take a look at how performance varies with reach type
res_info <- readRDS('data_DRB/DRB_spatial/segments_relative_to_reservoirs.rds')
res_metrics <- baseline_diff %>% left_join(res_info) %>%
  mutate(res_group = if_else(type_res %in% c('contains_reservoir',"within_reservoir", "downstream of reservoir (1)","downstream of reservoir (2)"), 'Impacted','Not Impacted', "reservoir_outlet_reach")) %>%
  group_by(res_group,metric) %>%
  summarise(RGCN = median(RGCN, na.rm=T),
            GraphWaveNet = median(GraphWaveNet, na.rm=T),
            count = n())

res_metrics <- baseline_diff %>% left_join(res_info) %>%
  group_by(type_res, metric) %>%
  summarise(RGCN = median(RGCN, na.rm=T),
            GraphWaveNet = median(GraphWaveNet, na.rm=T),
            count = n())

p2 <- baseline_diff %>% filter(metric == 'rmse_mean') %>% seg_plotter_sf(., 'metric_diff',ll=-1,ul=2, diff = T, network_color = 'white')+
  labs(title = 'RGCN minus GWN',subtitle='Blue=GWN outperformed RGCN', color = 'RMSE\nDifference') +
  theme(title = element_text(size =8))



p3 <- rgcn_stats$months %>% filter(partition == 'tst',train_type=='Full Train') %>% mutate(model= 'RGCN') %>%
  bind_rows(gwn_stats$months %>% filter(partition == 'tst',train_type=='Full Train') %>% mutate(model = 'GraphWaveNet')) %>%
  pivot_longer(c(rmse_mean, mean_bias_mean)) %>%
  mutate(name = factor(name, levels = c('rmse_mean', 'mean_bias_mean'), labels = c('RMSE','Bias')),
         month = month(date, label = T)) %>%
  ggplot(aes(x=month, y=value, fill=model, shape = name)) +
  scale_fill_viridis_d(end =.6) +
  #scale_y_continuous(breaks = c(0,1,2)) +
  geom_col(position = 'dodge') +
  facet_wrap(~name,nrow=2, scales='free_y') +
  theme_minimal() +
  labs(x = 'Month', y = '°Celsius',fill = ' ') +
  theme(axis.title = element_text(size=8))


layout <- rbind(c(1,1,1,2,2),
                c(1,1,1,2,2),
                c(1,1,1,2,2),
                c(3,3,3,3,3),
                c(3,3,3,3,3))

g <- gridExtra::grid.arrange(p1,p2,p3, layout_matrix = layout)

ggsave('../drb_gwnet/2_analysis/figures/baseline_comps.png', plot = g, width = 5, height = 5, units = 'in')

rgcn_stats$temps %>% mutate(model = 'RGCN') %>%
  bind_rows(gwn_stats$temps %>% mutate(model = 'GWN')) %>%
  filter(partition == 'tst',
         train_type == 'Full Train') %>%
  select(rmse_mean, rmse_top10_mean,rmse_bot10_mean, model) %>%
  pivot_longer(-model) %>%
  mutate(name = case_when(name == 'rmse_top10_mean'~ 'Warmest 10%',
                          name == 'rmse_bot10_mean'~ 'Coldest 10%',
                          name== 'rmse_mean'~ 'Overall')) %>%
  rename(`Temperature Bin` = name) %>%
  pivot_wider(names_from = model, values_from = value) %>%
  mutate(`GWN-RGCN` = GWN-RGCN) %>%
  mutate_if(is.numeric, round, digits=3) %>%
  relocate(RGCN, .after = GWN) %>%
  kableExtra::kbl(col.names = c('Temperature\nBin','GWN','RGCN','Difference(GWN-RGCN)')) %>%
  kableExtra::add_header_above(c('Overall RMSE by Temperature Bin' = 4)) %>%
  kableExtra::row_spec(2, bold = T, color = "white", background = "#FF7F7F") %>%
  kableExtra::row_spec(3, bold = T, color = 'white', background = '#528AAE') %>%
  kableExtra::row_spec(1, bold = T, color = 'grey') %>%
  kableExtra::kable_material(full_width = F)


rgcn_stats$temps %>% mutate(model = 'RGCN') %>%
  bind_rows(gwn_stats$temps %>% mutate(model = 'GWN')) %>%
  filter(partition == 'tst',
         train_type=='Full Train') %>%
  select(nse_mean, nse_top10_mean,nse_bot10_mean, model) %>%
  pivot_longer(-model) %>%
  mutate(name = case_when(name == 'nse_top10_mean'~ 'Warmest 10%',
                          name == 'nse_bot10_mean'~ 'Coldest 10%',
                          name== 'nse_mean'~ 'Overall')) %>%
  rename(`Temperature Bin` = name) %>%
  pivot_wider(names_from = model, values_from = value) %>%
  mutate(`GWN Improvement` = GWN-RGCN) %>%
  relocate(RGCN, .after = GWN) %>%
  kableExtra::kbl(col.names = c('Temperature\nBin','GWN','RGCN','Difference(GWN-RGCN)')) %>%
  kableExtra::add_header_above(c('Overall NSE by Temperature Bin' = 4)) %>%
  kableExtra::row_spec(2, bold = T, color = "white", background = "#FF7F7F") %>%
  kableExtra::row_spec(3, bold = T, color = 'white', background = '#528AAE') %>%
  kableExtra::row_spec(1, bold = T, color = 'grey') %>%
  kableExtra::kable_material(full_width = F)


p1 <- rgcn_stats$temps %>% 
  reshape_metric(.,'rmse',c('partition','run','model')) %>% mutate(model = 'RGCN') %>%
  bind_rows(gwn_stats$temps %>% reshape_metric(.,'rmse',c('partition','run','model')) %>% mutate(model='GWN')) %>%
  filter(partition =='tst') %>%
  ggplot(.,aes(x = group, y = mean, color = model)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd)) +
  theme_bw() +
  ggtitle('RMSE')

p2 <- rgcn_stats$temps %>%
  reshape_metric(.,'nse',c('partition','run','model')) %>% mutate(model = 'RGCN') %>%
  bind_rows(gwn_stats$temps %>% reshape_metric(.,'nse',c('partition','run','model')) %>% mutate(model='GWN')) %>%
  filter(partition =='tst') %>%
  ggplot(.,aes(x = group, y = mean, color = model)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd)) +
  theme_bw() +
  ggtitle('nse')

gridExtra::grid.arrange(p1,p2, ncol = 1, top = 'Mean and SD across replicates')


### Plot mean and sd
full_temps %>% filter(partition == 'tst') %>%
  reshape_metric(.,'rmse',c('partition','run','model')) %>%
  ggplot(.,aes(x = group, y = mean, color = model)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd)) +
  theme_bw() +
  ggtitle('rmse') +
  facet_wrap(~run, scales = 'free')
```

### LTO Comps

```{r}
metrics <- c('overall_metrics','month_metrics','reach_metrics')

gwn_lto_min <- metrics %>% map(~combine_replicates('results/LTO/GWN/min',.))
names(gwn_lto_min) <- c('temps','months','segs')

gwn_lto_max <- metrics %>% map(~combine_replicates('results/LTO/GWN/max', .))
names(gwn_lto_max) <- c('temps','months','segs')


rgcn_lto_min <- metrics %>% map(~combine_replicates('results/LTO/RGCN/min',.))
names(rgcn_lto_min) <- c('temps','months','segs')

rgcn_lto_max <- metrics %>% map(~combine_replicates('results/LTO/RGCN/max',.))
names(rgcn_lto_max) <- c('temps','months','segs')

rgcn_diff_min <- seg_error_diff(rgcn_stats$segs, rgcn_lto_min$segs, 'Baseline', 'Holdout',shape=edges)
rgcn_diff_max <- seg_error_diff(rgcn_stats$segs, rgcn_lto_max$segs, 'Baseline', 'Holdout',shape=edges)

gwn_diff_min <- seg_error_diff(gwn_stats$segs, gwn_lto_max$segs, 'Baseline', 'Holdout', shape=edges)
gwn_diff_max <- seg_error_diff(gwn_stats$segs, gwn_lto_max$segs, 'Baseline', 'Holdout',shape=edges)

full_temps <- rgcn_diff_max %>% mutate(model = 'RGCN', holdout = 'Max Temps') %>%
  bind_rows(rgcn_diff_min%>% mutate(model = 'RGCN', holdout = 'Min Temps')) %>%
  bind_rows(gwn_diff_max  %>% mutate(model = 'GWN', holdout = 'Max Temps')) %>%
  bind_rows(gwn_diff_min  %>% mutate(model = 'GWN', holdout = 'Min Temps')) %>%
  select(seg_id_nat, partition, metric, Baseline, Holdout, metric_diff, model,holdout)

sig_test_temps <- full_temps %>% ungroup() %>%
  group_by(holdout, model, metric, partition) %>%
  nest() %>%
  mutate(t.test = map(data, ~t.test(.$Holdout, .$Baseline, alternative='greater') %>% broom::tidy())) %>%
  select(-data) %>%
  unnest(cols = c(t.test)) %>%
  mutate(p.value = round(p.value,3))

full_temps %>% 
  filter(metric == 'rmse_mean') %>%
  seg_plotter_sf(., 'metric_diff',ll=-2,ul=2, diff = T, network_color = 'white') +
  facet_grid(holdout~model) 
  
ggsave('2_analysis/figures/lto_spatial.png', width = 4, height = 5, units = 'in')

full <- full %>% mutate_all(~ifelse(is.nan(.), NA, .))

lto_full_segs <- gwn_lto_min$segs %>% mutate(run = 'Train Hot/Test Cold', model='GWN') %>%
  bind_rows(gwn_lto_max$segs %>% mutate(run = 'Train Cold/Test Hot', model='GWN')) %>%
  bind_rows(rgcn_lto_max$segs %>% mutate(run = 'Train Cold/Test Hot', model = 'RGCN')) %>%
  bind_rows(rgcn_lto_min$segs %>% mutate(run = 'Train Hot/Test Cold', model = 'RGCN')) %>%
  bind_rows(gwn_stats$segs %>% mutate(run = 'Baseline') %>% mutate(model = 'GWN')) %>%
  bind_rows(rgcn_stats$segs %>% mutate(run = 'Baseline', model = 'RGCN')) %>%
  filter(partition == 'tst')

meds <- lto_full_segs %>% 
    reshape_metric(.,'rmse',c('partition','seg_id_nat','run','model')) %>%
    filter(is.finite(mean)) %>%
    group_by(model, run, group) %>%
    summarise(med = round(median(mean, na.rm = T),2))

lto_full_segs %>% 
  reshape_metric(.,'rmse',c('partition','seg_id_nat','run','model')) %>%
  filter(is.finite(mean),
         group == 'rmse') %>%
  ggplot(., aes(x = run, y = mean))+
  geom_violin(width = .5,aes(fill = run),alpha =.5) +
  geom_boxplot(width = .3) +
  coord_cartesian(ylim=c(.75,3)) +
  scale_fill_manual(values=c('grey80',scales::muted('red'),scales::muted('blue'))) +
  geom_text(data = meds %>% filter(group == 'rmse'), aes(x = run, y = med, label = med), 
            size = 3, vjust = -1.5)+
  theme_bw()+
  labs(title = 'Test Error Distribution for Temperature Holdouts', fill = 'Holdout run', y='RMSE across stream reaches') +
  theme(legend.position = 'bottom',axis.title.x = element_blank(),
      axis.text.x = element_blank()) +
  facet_wrap(~model)

ggsave('../drb_gwnet/2_analysis/figures/LTO_Segs_Violin.png', width = 5.5, height =4, units = 'in')

lto_full_temps <- 
  gwn_lto_min$temps %>% mutate(run = 'Train Hot/Test Cold', model='GWN') %>%
  bind_rows(gwn_lto_max$temps %>% mutate(run = 'Train Cold/Test Hot', model='GWN')) %>%
  bind_rows(rgcn_lto_max$temps %>% mutate(run = 'Train Cold/Test Hot', model = 'RGCN')) %>%
  bind_rows(rgcn_lto_min$temps %>% mutate(run = 'Train Hot/Test Cold', model = 'RGCN')) %>%
  bind_rows(gwn_stats$temps %>% mutate(run = 'Baseline') %>% mutate(model = 'GWN')) %>%
  bind_rows(rgcn_stats$temps %>% mutate(run = 'Baseline', model = 'RGCN')) %>%
  filter(partition == 'tst')
  

lto_full_temps %>%
  reshape_metric(.,'nse',c('partition','run','model')) %>%
  filter(is.finite(mean)) %>%
  ggplot(., aes(x= group, color = run, y = mean))+
  geom_point(position=position_dodge(.3)) +
  geom_errorbar(aes(ymin = mean-sd, ymax=mean+sd), position = position_dodge(.3)) +
  facet_wrap(~model)


lto_full_temps %>%
  reshape_metric(.,'rmse',c('partition','run','model')) %>%
  filter(is.finite(mean)) %>%
  ggplot(., aes(x= group, color = run, y = mean))+
  geom_point(position=position_dodge(.3)) +
  geom_errorbar(aes(ymin = mean-sd, ymax=mean+sd), position = position_dodge(.3)) +
  facet_wrap(~model)
```


### LLO Comps

```{r}
llo_groups <- read_csv('data_DRB/DRB_spatial/llo_groups.csv')

rgcn_llo <- metrics %>% map(~combine_replicates('results/LLO/RGCN',., subfolders = T))
names(rgcn_llo) <- c('temps','months','segs')

gwn_llo <-  metrics %>% map(~combine_replicates('results/LLO/GWN',., subfolders = T))
names(gwn_llo) <- c('temps','months','segs')

p1 <- rgcn_llo$segs %>% mutate(model = 'RGCN') %>% filter(is.finite(rmse_mean)) %>%
  bind_rows(gwn_llo$segs %>% mutate(model = 'GWN') %>% filter(is.finite(rmse_mean))) %>%
  seg_plotter_sf(., 'rmse_mean') +
  facet_wrap(~model, nrow =1)

rgcn_diff <- seg_error_diff(rgcn_stats$segs, rgcn_llo$segs %>% select(-run), 'Baseline', 'Holdout', shape = edges) %>% filter(is.finite(metric_diff))

gwn_diff <- seg_error_diff(gwn_stats$segs, gwn_llo$segs %>% select(-run), 'Baseline', 'Holdout', shape = edges) %>% filter(is.finite(metric_diff))

full_diff_llo <- gwn_diff %>% select(seg_id_nat, partition, metric, metric_diff) %>% mutate(model = 'GWN') %>%
  bind_rows(rgcn_diff %>% select(seg_id_nat, partition, metric, metric_diff) %>% mutate(model = 'RGCN'))

p2 <-full_diff_llo %>% 
  mutate(metric_diff = ifelse(metric_diff > 3, 3, ifelse(metric_diff < -1, -1, metric_diff))) %>%
  filter(metric == 'rmse_mean', partition == 'tst') %>%
  seg_plotter_sf(., 'metric_diff') +
  #scale_color_gradient2(na.value = 'white', mid = 'grey80', name = 'RMSE\nDifference', breaks = c(-3,-1.5,0,1.5,3),labels = c('<-3', '-1.5', "0", '1.5', '>3')) +
  scale_color_gradient2(na.value = 'white', mid = 'grey80', name = 'RMSE\nDifference') +
  facet_wrap(~model) 

g <- gridExtra::grid.arrange(p1,p2, nrow =2)

ggsave('../drb_gwnet/2_analysis/figures/llo_spatial.png',plot=g, width = 4,height = 6, units = 'in')  

#### Appalachains and Piedmont labels are swapped, need to correct for plotting.
llo_full_segs <- gwn_llo$segs %>% mutate(model='GWN') %>%
  bind_rows(rgcn_llo$segs %>% mutate(model = 'RGCN')) %>%
  filter(partition == 'tst') %>%
  left_join(llo_groups) %>%
  mutate(test_group=factor(test_group, levels = c('Coastal_Plains','Appalachians','Piedmont'),
                           labels = c('Coastal','Piedmont', 'Headwaters')))
  

llo_diff_segs <- rgcn_diff %>% mutate(model = 'RGCN') %>%
  bind_rows(gwn_diff %>% mutate(model = 'GWN')) %>%
  left_join(llo_groups) %>%
  mutate(test_group=factor(test_group, levels = c('Coastal_Plains','Appalachians','Piedmont'),
                           labels = c('Coastal','Piedmont', 'Headwaters')))

llo_diff_segs %>%
  filter(partition == 'tst') %>%
  group_by(model, metric) %>%
  summarise(mean_diff = round(mean(metric_diff, na.rm = T),3),
            sd_dff = round(sd(metric_diff, na.rm = T),3),
            median = round(median(metric_diff, na.rm = T),3))

# sig_test <- llo_full_segs %>%
#   filter(!is.na(metric_diff)) %>%
#   select(-c(Baseline, Holdout)) %>%
#   pivot_wider(names_from = model, values_from = metric_diff) %>%
#   group_by(test_group, metric, partition) %>%
#   nest() %>%
#   mutate(wilcox = map(data, ~wilcox.test(.$GWN, .$RGCN, paired = T) %>% broom::tidy())) %>%
#   select(-data) %>%
#   unnest(cols = c(wilcox)) %>%
#   mutate(p.value = round(p.value,4))

sig_test <- llo_full_segs %>%
  filter(!is.na(metric_diff), partition == 'tst') %>%
  group_by(test_group, model, metric) %>%
  nest() %>%
  mutate(wilcox = map(data, ~wilcox.test(.$Baseline, .$Holdout) %>% broom::tidy())) %>%
  select(-data) %>%
  unnest(cols = c(wilcox)) %>%
  mutate(p.value = round(p.value,3))

llo_diff <- llo_full_segs %>% group_by(model, metric, test_group) %>%
  summarize(Baseline = median(Baseline),
            Holdout = median(Holdout),
            Diff = Holdout-Baseline) %>%
  mutate(Diff = round(Diff,2))
  
llo_full_segs %>% filter(!is.na(metric_diff), partition == 'tst', metric == 'rmse_mean') %>%
  select(-metric_diff) %>%
  pivot_longer(c(Baseline, Holdout)) %>%
  ggplot(., aes(x = value, y = test_group)) +
    geom_density_ridges(aes(fill=name),
    quantile_lines = TRUE, quantiles = .5, scale = 0.9, alpha = 0.7,
    vline_size = 1) +
   geom_text(data = llo_diff %>% filter(metric == 'rmse_mean'), 
             aes(x = 5, y = test_group, label = paste0("Δ RMSE: ",Diff)), size = 3, vjust = -2)+
  scale_fill_viridis_d(alpha = .3, end = .6) +
  coord_cartesian(xlim=c(0,7)) +
  facet_wrap(~model, nrow=2) +
  #coord_cartesian(xlim=c(0,8)) +
  labs(x = 'RMSE', y='Holdout Region', fill = 'Model Run') +
  theme_bw() +
  theme(legend.position = 'bottom') +
  labs(title = "Test Error Distribution for\nLocation Holdouts")

ggsave('../drb_gwnet/2_analysis/figures/LLO_ridges_rmse.png',width = 3.5,height=5, units = 'in')
  
llo_full_segs %>% filter(!is.na(metric_diff), partition == 'tst', metric == 'nse_mean') %>%
  select(-metric_diff) %>%
  pivot_longer(c(Baseline, Holdout)) %>%
  ggplot(., aes(x = value, y = test_group)) +
    geom_density_ridges(aes(fill=name),
    quantile_lines = TRUE, quantiles = .5, scale = 0.9, alpha = 0.7,
    vline_size = 1) +
   geom_text(data =llo_diff %>% filter(metric == 'nse_mean'), 
             aes(x = 0, y = test_group, label = paste0("Δ NSE: ",Diff)), size = 3, vjust = -2)+
  scale_fill_viridis_d(alpha = .3, end = .6) +
  #coord_cartesian(xlim=c(0,1.5)) +
  facet_wrap(~model, nrow=2) +
  coord_cartesian(xlim=c(-1,1)) +
  labs(x = 'NSE', y='Holdout Region', fill = 'Model Run') +
  theme_bw()

ggsave('../drb_gwnet/2_analysis/figures/LLO_ridges_nse.png',width = 3.5,height=5, units = 'in')

llo_full_temps <- 
  gwn_llo$temps %>% mutate(model='GWN') %>%
  bind_rows(rgcn_llo$temps %>% mutate(model = 'RGCN')) %>%
  bind_rows(gwn_stats$temps %>% mutate(run = 'Baseline') %>% mutate(model = 'GWN')) %>%
  bind_rows(rgcn_stats$temps %>% mutate(run = 'Baseline', model = 'RGCN')) %>%
  filter(partition == 'tst') %>%
  mutate(run=factor(run, levels = c('coastal','appalachians','piedmont'),
                           labels = c('Coastal','Piedmont', 'Headwaters')))

llo_full_temps %>%
  reshape_metric(.,'rmse',c('partition','run','model')) %>%
  ggplot(.,aes(x= group, color = run, y = mean))+
  geom_point(position=position_dodge(.3)) +
  geom_errorbar(aes(ymin = mean-sd, ymax=mean+sd), position = position_dodge(.3)) +
  facet_wrap(~model)


##
res_info <- readRDS('data_DRB/DRB_spatial/segments_relative_to_reservoirs.rds')
llo_gwn_rmse_sf <- llo_full_segs %>% 
  filter(!is.na(metric_diff), 
         partition == 'tst', 
         metric == 'rmse_mean',
         model == 'GWN') %>%
  inner_join(edges %>% select(seg_id_nat)) %>%
  left_join(res_info) %>%
  st_as_sf()


llo_gwn_rmse_sf %>% st_set_geometry(NULL) %>% group_by(type_res,test_group) %>%
  summarise(mean_delta_rmse = mean(metric_diff),
            count = n()) %>%
  arrange(mean_delta_rmse)

p1 <- ggplot(llo_groups %>% mutate(test_group=factor(test_group, 
                                                     levels = c('Coastal_Plains','Appalachians','Piedmont'),
                                                     labels = c('Coastal','Piedmont', 'Headwaters'))) %>%
               right_join(edges) %>% st_as_sf()) +
  geom_sf(aes(color=test_group))

p2 <- ggplot(edges %>% select(seg_id_nat)%>% left_join(res_info)) +
  geom_sf(aes(color=type_res))

gridExtra::grid.arrange(p1,p2, nrow = 1)

mapview(edges %>% select(seg_id_nat)%>% left_join(res_info) %>% st_transform(4326),zcol='type_res')

res_info %>% left_join(llo_groups) %>%
  group_by(test_group,type_res) %>%
  summarise(count = n()) %>%
  filter(type_res == 'contains_reservoir')

llo_groups %>% mutate(test_group=factor(test_group, 
                                        levels = c('Coastal_Plains','Appalachians','Piedmont'),
                                        labels = c('Coastal','Piedmont', 'Headwaters'))) %>%
  left_join(res_info) %>%
  group_by(test_group,type_res) %>%
  summarise(count = n()) %>%
  filter(type_res %in% c('contains_reservoir', 'within_reservoir'))
```

###Drought Comps

```{r}
metrics <- c('overall_metrics','month_metrics','reach_metrics')

gwn_drought <- metrics %>% map(~combine_replicates('results/Drought/GWN',.))
names(gwn_drought) <- c('temps','months','segs')

rgcn_drought <- metrics %>% map(~combine_replicates('results/Drought/RGCN',.))
names(rgcn_drought) <- c('temps','months','segs')

rgcn_diff_d <- seg_error_diff(rgcn_stats$segs, rgcn_drought$segs, 'Baseline', 'Holdout',shape=edges)

gwn_diff_d <- seg_error_diff(gwn_stats$segs, gwn_drought$segs, 'Baseline', 'Holdout', shape=edges)

full_diff_drought <- rgcn_diff_d %>% mutate(model = 'RGCN', holdout = 'Drought') %>%
  bind_rows(gwn_diff_d  %>% mutate(model = 'GWN', holdout = 'Drought')) %>%
  select(seg_id_nat, partition, metric, Baseline, Holdout, metric_diff, model,holdout)

sig_test_drought <- full_diff_drought %>% ungroup() %>%
  group_by(holdout, model, metric, partition) %>%
  nest() %>%
  mutate(wilcox = map(data, ~wilcox.test(.$Baseline, .$Holdout, paired =T) %>% broom::tidy())) %>%
  select(-data) %>%
  unnest(cols = c(wilcox)) %>%
  mutate(p.value = round(p.value,3))

full_diff_drought %>% 
  filter(metric == 'rmse_mean') %>%
  seg_plotter_sf(., 'metric_diff',ll=-2,ul=2, diff = T, network_color = 'white') +
  facet_grid(holdout~model) 
  
ggsave('2_analysis/figures/drought_spatial.png', width = 4, height = 5, units = 'in')

drought_full_segs <- gwn_drought$segs %>% mutate(run = 'Drought', model='GWN') %>%
  bind_rows(rgcn_drought$segs %>% mutate(run = 'Drought', model = 'RGCN')) %>%
  bind_rows(gwn_stats$segs %>% mutate(run = 'Baseline') %>% mutate(model = 'GWN')) %>%
  bind_rows(rgcn_stats$segs %>% mutate(run = 'Baseline', model = 'RGCN')) %>%
  filter(partition == 'tst')


meds <- drought_full_segs %>%
  reshape_metric(.,'rmse',c('partition','seg_id_nat','run','model')) %>%
  filter(is.finite(mean),
         group == 'rmse') %>%
  group_by(model, run, group) %>%
  summarise(med = median(mean, na.rm = T) %>% round(.,2))

drought_full_segs %>% 
  reshape_metric(.,'rmse',c('partition','seg_id_nat','run','model')) %>%
  filter(is.finite(mean),
         group == 'rmse') %>%
  ggplot(., aes(x = run, y = mean))+
  geom_violin(width = .5,aes(fill = run),alpha =.5) +
  geom_boxplot(width = .3) +
  coord_cartesian(ylim=c(.75,3)) +
  scale_fill_manual(values=c('grey80',scales::muted('red'),scales::muted('blue'))) +
  geom_text(data = meds %>% filter(group == 'rmse'), aes(x = run, y = med, label = med), 
              size = 3, vjust = -1.5)+
  theme_bw()+
  labs(title = 'Test Error Distribution for Temperature Holdouts', fill = 'Holdout run', y='RMSE across stream reaches') +
  theme(legend.position = 'bottom',axis.title.x = element_blank(),
        axis.text.x = element_blank()) +
  facet_wrap(~model)

ggsave('../drb_gwnet/2_analysis/figures/Drought_Segs_Violin.png', width = 5.5, height =4, units = 'in')

drought_full_temps <- 
  gwn_drought$temps %>% mutate(run = 'Drought', model='GWN') %>%
  bind_rows(rgcn_drought$temps %>% mutate(run = 'Drought', model = 'RGCN')) %>%
  bind_rows(gwn_stats$temps %>% mutate(run = 'Baseline') %>% mutate(model = 'GWN')) %>%
  bind_rows(rgcn_stats$temps %>% mutate(run = 'Baseline', model = 'RGCN')) %>%
  filter(partition == 'tst')

drought_full_temps %>% 
  reshape_metric(.,'rmse',c('partition','run','model')) %>%
  filter(is.finite(mean)) %>% 
  ggplot(., aes(x= group, color = run, y = mean))+
  geom_point(position=position_dodge(.3)) +
  geom_errorbar(aes(ymin = mean-sd, ymax=mean+sd), position = position_dodge(.3)) +
  facet_wrap(~model)

drought_full_temps %>% 
  reshape_metric(.,'nse',c('partition','run','model')) %>%
  filter(is.finite(mean)) %>%
  ggplot(., aes(x= group, color = run, y = mean))+
  geom_point(position=position_dodge(.3)) +
  geom_errorbar(aes(ymin = mean-sd, ymax=mean+sd), position = position_dodge(.3)) +
  facet_wrap(~model)

```


### Make some summary figs that summarize all the hold-out experiments

```{r}
rmse_temp_summary <- drought_full_temps %>% 
  reshape_metric(.,'rmse',c('partition','run','model')) %>%
  filter(is.finite(mean)) %>%
  bind_rows(llo_full_temps %>%
    reshape_metric(.,'rmse',c('partition','run','model')) %>%
    filter(is.finite(mean))) %>%
  bind_rows(lto_full_temps%>% 
    reshape_metric(.,'rmse',c('partition','run','model')) %>%
    filter(is.finite(mean))) %>%
  distinct() #remove redundant baselines

baseline <- rmse_temp_summary %>% filter(run == 'Baseline') %>% 
  select(-run) %>%
  rename(baseline_mean=mean, baseline_sd=sd)

rmse_temp_summary <- rmse_temp_summary %>%
  filter(run!='Baseline') %>%
  left_join(baseline) %>%
  mutate(performance_change = baseline_mean-mean,
         group= factor(group, levels=c('rmse','rmse_bot10','rmse_top10'),
                       labels=c('Overall','Coldest 10%','Warmest 10%')),
         run = factor(run, levels = c("Train Hot/Test Cold","Train Cold/Test Hot", "Drought","Coastal","Piedmont","Headwaters"))
  ) %>%
  filter(!is.na(sd))

####
ggplot(rmse_temp_summary, aes(x=run, y=performance_change,fill = model)) +
  #geom_segment( aes(x=run, xend=run, y=0, yend=performance_change), position = position_dodge(.3)) +
  #geom_point(size=4, position = position_dodge(.3)) +
  geom_col(position='dodge')+
  geom_hline(aes(yintercept=0),color = 'black') +
  scale_fill_viridis_d(end=.6)+
  theme_bw() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = 'top'
  ) +
  coord_flip() +
  xlab("") +
  ylab("Change in RMSE from Baseline (Negative == Worse Performance)") +
  facet_wrap(~group)

ggsave('../drb_gwnet/2_analysis/figures/Overall_Performance_Change_temps.png',width = 6.5,height=3.5, units = 'in')


##### Just hot and drought for poster
rmse_temp_summary %>%
  filter(run %in% c("Drought","Train Cold/Test Hot"),
         group %in% c("Overall","Warmest 10%")) %>%
  mutate(run= factor(run, levels= c("Drought","Train Cold/Test Hot"), 
                     labels=c("Dryer Conditions","Warmer Conditions")),
         group=factor(group, levels=c("Overall","Warmest 10%"),
                      labels=c("Overall Performance","Warmest 10% of Predictions"))) %>%
  ggplot(., aes(x=run, y=performance_change,fill = model)) +
    geom_col(position='dodge')+
    geom_hline(aes(yintercept=0),color = 'black') +
    scale_fill_viridis_d(end=.6)+
    theme_bw() +
    theme(
      #panel.grid.major.x = element_blank(),
      #panel.border = element_blank(),
      #axis.ticks.x = element_blank(),
      legend.position = 'bottom'
    ) +
    coord_flip() +
    labs(x="",y="Δ RMSE (ºC)", title="Loss of Performance when\nGeneralizing to...", fill = "Model") +
    facet_wrap(~group,ncol=1)

ggsave('../drb_gwnet/2_analysis/figures/PosterOverallPerformance.png',width = 4,height=6, units = 'in', dpi=300)


rmse_seg_summary <- drought_full_segs %>% 
  reshape_metric(.,'rmse',c('seg_id_nat','partition','run','model')) %>%
  filter(is.finite(mean)) %>%
  bind_rows(llo_full_segs %>% select(-run) %>%
              rename(run = test_group) %>%
    reshape_metric(.,'rmse',c('seg_id_nat','partition','run','model')) %>%
    filter(is.finite(mean))) %>%
  bind_rows(lto_full_segs%>% 
    reshape_metric(.,'rmse',c('seg_id_nat','partition','run','model')) %>%
      filter(is.finite(mean)))  %>%
  filter(is.finite(sd)) %>%
  distinct() %>%
  mutate(group= factor(group, levels=c('rmse','rmse_bot10','rmse_top10'),
                       labels=c('Overall','Coldest 10%','Warmest 10%')),
         run = factor(run, levels = c("Train Hot/Test Cold","Train Cold/Test Hot", "Drought","Coastal","Piedmont","Headwaters",'Baseline')))

sig_test_summary_absolute <- rmse_seg_summary %>% ungroup() %>%
  filter(!is.na(sd)) %>%
  group_by(run, group) %>%
  nest() %>%
  mutate(wilcox = map(data, ~wilcox.test(.$mean[.$model=='GWN'],.$mean[.$model=='RGCN']) %>% broom::tidy())) %>%
  select(-data) %>%
  unnest(cols = c(wilcox)) %>%
  mutate(p.value = round(p.value,3)) %>%
  mutate(sig_symbol = case_when(p.value<0.01~'***',
                                p.value<0.05~'**',
                                p.value<0.1~'*'))

sig_test_paired <- rmse_seg_summary %>% ungroup() %>%
  filter(!is.na(sd)) %>%
  select(-sd) %>%
  pivot_wider(names_from='model',values_from='mean')%>%
  group_by(run, group) %>%
  nest() %>%
  mutate(wilcox = map(data, ~wilcox.test(.$GWN,.$RGCN,paired=T) %>% broom::tidy())) %>%
  select(-data) %>%
  unnest(cols = c(wilcox)) %>%
  mutate(p.value = round(p.value,3)) %>%
  mutate(sig_symbol = case_when(p.value<0.01~'***',
                                p.value<0.05~'**',
                                p.value<0.1~'*'))

ggplot(rmse_seg_summary, aes(y=run, x=mean)) +
  stat_density_ridges(aes(fill=model),quantile_lines = TRUE, quantiles = c(.5), alpha = 0.5, scale = 1.3) +
  scale_fill_viridis_d(end=.7) +
  coord_cartesian(c(0,5)) +
  geom_text(data=sig_test_paired,aes(x=0,y=run,label=sig_symbol),color='red',vjust=-1) +
  facet_wrap(~group,nrow=1)  +
  labs(x= 'Perfomance Across Reaches (RMSE °C)',y= 'Model Run',fill = 'Model') +
  theme_bw() +
  theme(legend.position = 'top') 

ggsave('../drb_gwnet/2_analysis/figures/Overall_Performance_Paired_Segs.png',width = 6.5,height=3.5, units = 'in')

rmse_seg_summary %>%
  filter(run %in% c("Baseline","Drought","Train Cold/Test Hot"),
         group =='Overall')%>%
ggplot(., aes(y=run, x=mean)) +
  stat_density_ridges(aes(fill=model),quantile_lines = TRUE, quantiles = c(.25,.5,.75), alpha = 0.5, scale = 1.3) +
  scale_fill_viridis_d(end=.7) +
  coord_cartesian(xlim=c(.5,3)) +
  #geom_text(data=sig_test_paired,aes(x=0,y=run,label=sig_symbol),color='red',vjust=-1) +
  facet_wrap(~group,nrow=1)  +
  labs(x= 'Perfomance Across Reaches (RMSE °C)',y= 'Model Run',fill = 'Model') +
  theme_bw() +
  theme(legend.position = 'top') 

baseline_seg <- rmse_seg_summary %>% filter(run == 'Baseline') %>% 
  select(-run) %>%
  rename(baseline_mean=mean, baseline_sd=sd)

rmse_seg_summary <- rmse_seg_summary %>%
  filter(run!='Baseline',!is.na(sd)) %>%
  left_join(baseline_seg) %>%
  mutate(performance_change = baseline_mean-mean)

# 
# sig_test_summary <- rmse_seg_summary %>% ungroup() %>%
#   group_by(run, group) %>%
#   nest() %>%
#   mutate(wilcox = map(data, ~wilcox.test(.$performance_change[.$model=='GWN'],.$performance_change[.$model=='RGCN'],alternative='g') %>% broom::tidy())) %>%
#   select(-data) %>%
#   unnest(cols = c(wilcox)) %>%
#   mutate(p.value = round(p.value,3)) %>%
#   mutate(sig_symbol = case_when(p.value<0.01~'***',
#                                 p.value<0.05~'**',
#                                 p.value<0.1~'*'))


sig_test_summary <- rmse_seg_summary %>% ungroup() %>%
  select(model, seg_id_nat,performance_change,group, run) %>%
  pivot_wider(names_from='model',values_from='performance_change')%>%
  group_by(run, group) %>%
  nest() %>%
  mutate(wilcox = map(data, ~wilcox.test(.$GWN,.$RGCN,alternative='g', paired=T) %>% broom::tidy())) %>%
  select(-data) %>%
  unnest(cols = c(wilcox)) %>%
  mutate(p.value = round(p.value,3)) %>%
  mutate(sig_symbol = case_when(p.value<0.01~'***',
                                p.value<0.05~'**',
                                p.value<0.1~'*'))  

ggplot(rmse_seg_summary, aes(x=run, y=performance_change, fill = model)) +
  geom_violin(draw_quantiles = c(.25,.5,.75)) +
  coord_cartesian(c(-7,5)) +
  coord_flip() +
  facet_wrap(~group,nrow=3)

ggplot(rmse_seg_summary, aes(y=run, x=performance_change)) +
  stat_density_ridges(aes(fill=model),quantile_lines = TRUE, quantiles = c(.5), alpha = 0.5, scale = 1.3) +
  scale_fill_viridis_d(end=.7) +
  geom_vline(aes(xintercept=0),color = 'red') +
  #coord_cartesian(c(-5,2.5)) +
  geom_text(data=sig_test_summary,aes(x=2,y=run,label=sig_symbol),color='red',vjust=-1) +
  facet_wrap(~group,nrow=1)  +
  labs(x= 'Change in Perfomance Across Reaches (RMSE °C)',y= 'Holdout Experiment',fill = 'Model') +
  theme_bw() +
  theme(legend.position = 'top')

ggsave('../drb_gwnet/2_analysis/figures/Overall_Performance_Change_Segs.png',width = 6.5,height=3.5, units = 'in')

rmse_seg_summary %>%
  filter(run == 'Drought'|run=='Train Cold/Test Hot') %>%
  group_by(run, model, group) %>%
  summarise(performance_change = median(performance_change, na.rm=T)) %>%
  ggplot(., aes(x=run, y=performance_change)) +
  #geom_segment( aes(x=run, xend=run, y=0, yend=performance_change), position = position_dodge(.3)) +
  #geom_point(size=4, position = position_dodge(.3)) +
  geom_col(aes(fill = model),position='dodge')+
  geom_hline(aes(yintercept=0),color = 'black') +
  scale_fill_viridis_d(end=.6)+
  #geom_text(data=sig_test_summary,aes(x=run,y=-1,label=sig_symbol),color='red',vjust=-1) +
  theme_bw() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = 'top'
  ) +
  coord_flip()+#ylim=c(-1.5,.5)) +
  #coord_cartesian(xlim=c(-1,.5)) +
  xlab("") +
  ylab("Change in RMSE from Baseline (Negative == Worse Performance)") +
  facet_wrap(~group)

ggsave('../drb_gwnet/2_analysis/figures/Overall_Performance_Change_Segs.png',width = 6.5,height=3.5, units = 'in')
```

### Same as above but for NSE

```{r}
nse_temp_summary <- drought_full_temps %>% 
  reshape_metric(.,'nse',c('partition','run','model')) %>%
  filter(is.finite(mean)) %>%
  bind_rows(llo_full_temps %>%
    reshape_metric(.,'nse',c('partition','run','model')) %>%
    filter(is.finite(mean))) %>%
  bind_rows(lto_full_temps%>% 
    reshape_metric(.,'nse',c('partition','run','model')) %>%
    filter(is.finite(mean))) %>%
  distinct() #remove redundant baselines

baseline <- nse_temp_summary %>% filter(run == 'Baseline') %>% 
  select(-run) %>%
  rename(baseline_mean=mean, baseline_sd=sd)

nse_temp_summary <- nse_temp_summary %>%
  filter(run!='Baseline') %>%
  left_join(baseline) %>%
  mutate(performance_change = baseline_mean-mean,
         group= factor(group, levels=c('nse','nse_bot10','nse_top10'),
                       labels=c('Overall','Coldest 10%','Warmest 10%')),
         run = factor(run, levels = c("Train Hot/Test Cold","Train Cold/Test Hot", "Drought","Coastal","Piedmont","Headwaters"))
  ) %>%
  filter(!is.na(sd))

####
ggplot(nse_temp_summary, aes(x=run, y=performance_change,fill = model)) +
  #geom_segment( aes(x=run, xend=run, y=0, yend=performance_change), position = position_dodge(.3)) +
  #geom_point(size=4, position = position_dodge(.3)) +
  geom_col(position='dodge')+
  geom_hline(aes(yintercept=0),color = 'black') +
  scale_fill_viridis_d(end=.6)+
  theme_bw() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = 'top'
  ) +
  coord_flip() +
  xlab("") +
  ylab("Change in nse from Baseline (Negative == Worse Performance)") +
  facet_wrap(~group)

ggsave('../drb_gwnet/2_analysis/figures/Overall_Performance_Change_temps_nse.png',width = 6.5,height=3.5, units = 'in')

nse_seg_summary <- drought_full_segs %>% 
  reshape_metric(.,'nse',c('seg_id_nat','partition','run','model')) %>%
  filter(is.finite(mean)) %>%
  bind_rows(llo_full_segs %>% select(-run) %>%
              rename(run = test_group) %>%
    reshape_metric(.,'nse',c('seg_id_nat','partition','run','model')) %>%
    filter(is.finite(mean))) %>%
  bind_rows(lto_full_segs%>% 
    reshape_metric(.,'nse',c('seg_id_nat','partition','run','model')))  %>%
  distinct()

ggplot(nse_seg_summary %>% filter(group =='nse'), aes(x=mean, color = run)) +
  stat_ecdf(geom = "line") +
  #stat_summary(aes(y=mean,xintercept=stat(y),),fun='median',geom='vline')+
  facet_wrap(~model) +
  coord_cartesian(xlim=c(-5,1))

sig_test_summary_absolute <- nse_seg_summary %>% ungroup() %>%
  filter(!is.na(sd)) %>%
  group_by(run, group) %>%
  nest() %>%
  mutate(wilcox = map(data, ~wilcox.test(.$mean[.$model=='GWN'],.$mean[.$model=='RGCN']) %>% broom::tidy())) %>%
  select(-data) %>%
  unnest(cols = c(wilcox)) %>%
  mutate(p.value = round(p.value,3)) %>%
  mutate(sig_symbol = case_when(p.value<0.01~'***',
                                p.value<0.05~'**',
                                p.value<0.1~'*'))

sig_test_paired <- nse_seg_summary %>% ungroup() %>%
  filter(!is.na(sd)) %>%
  select(-sd) %>%
  pivot_wider(names_from='model',values_from='mean')%>%
  group_by(run, group) %>%
  nest() %>%
  mutate(wilcox = map(data, ~wilcox.test(.$GWN,.$RGCN,paired=T) %>% broom::tidy())) %>%
  select(-data) %>%
  unnest(cols = c(wilcox)) %>%
  mutate(p.value = round(p.value,3)) %>%
  mutate(sig_symbol = case_when(p.value<0.01~'***',
                                p.value<0.05~'**',
                                p.value<0.1~'*'))

ggplot(nse_seg_summary, aes(x=mean, color = model)) +
  stat_ecdf(geom = "line") +
  facet_grid(run~group) +
  coord_cartesian(xlim=c(0,1))
  
  stat_density_ridges(aes(fill=model),quantile_lines = TRUE, quantiles = c(.5), alpha = 0.5, scale = 1.3) +
  scale_fill_viridis_d(end=.7) +
  coord_cartesian(c(0,5)) +
  geom_text(data=sig_test_paired,aes(x=0,y=run,label=sig_symbol),color='red',vjust=-1) +
  facet_wrap(~group,nrow=1)  +
  labs(x= 'Perfomance Across Reaches (nse °C)',y= 'Model Run',fill = 'Model') +
  theme_bw() +
  theme(legend.position = 'top')

ggsave('../drb_gwnet/2_analysis/figures/Overall_Performance_Absolute_Segs.png',width = 6.5,height=3.5, units = 'in')

baseline_seg <- nse_seg_summary %>% filter(run == 'Baseline') %>% 
  select(-run) %>%
  rename(baseline_mean=mean, baseline_sd=sd)

nse_seg_summary <- nse_seg_summary %>%
  filter(run!='Baseline',!is.na(sd)) %>%
  left_join(baseline) %>%
  mutate(performance_change = baseline_mean-mean,
         group= factor(group, levels=c('nse','nse_bot10','nse_top10'),
                       labels=c('Overall','Coldest 10%','Warmest 10%')),
         run = factor(run, levels = c("Train Hot/Test Cold","Train Cold/Test Hot", "Drought","Coastal","Piedmont","Headwaters"))
)
# 
# sig_test_summary <- nse_seg_summary %>% ungroup() %>%
#   group_by(run, group) %>%
#   nest() %>%
#   mutate(wilcox = map(data, ~wilcox.test(.$performance_change[.$model=='GWN'],.$performance_change[.$model=='RGCN'],alternative='g') %>% broom::tidy())) %>%
#   select(-data) %>%
#   unnest(cols = c(wilcox)) %>%
#   mutate(p.value = round(p.value,3)) %>%
#   mutate(sig_symbol = case_when(p.value<0.01~'***',
#                                 p.value<0.05~'**',
#                                 p.value<0.1~'*'))


sig_test_summary <- nse_seg_summary %>% ungroup() %>%
  select(model, seg_id_nat,performance_change,group, run) %>%
  pivot_wider(names_from='model',values_from='performance_change')%>%
  group_by(run, group) %>%
  nest() %>%
  mutate(wilcox = map(data, ~wilcox.test(.$GWN,.$RGCN,alternative='g', paired=T) %>% broom::tidy())) %>%
  select(-data) %>%
  unnest(cols = c(wilcox)) %>%
  mutate(p.value = round(p.value,3)) %>%
  mutate(sig_symbol = case_when(p.value<0.01~'***',
                                p.value<0.05~'**',
                                p.value<0.1~'*'))  

ggplot(nse_seg_summary, aes(x=run, y=performance_change, fill = model)) +
  geom_violin(draw_quantiles = c(.25,.5,.75)) +
  coord_cartesian(c(-7,5)) +
  coord_flip() +
  facet_wrap(~group,nrow=3)

ggplot(nse_seg_summary, aes(y=run, x=performance_change)) +
  stat_density_ridges(aes(fill=model),quantile_lines = TRUE, quantiles = c(.5), alpha = 0.5, scale = 1.3) +
  scale_fill_viridis_d(end=.7) +
  geom_vline(aes(xintercept=0),color = 'red') +
  coord_cartesian(c(-5,2.5)) +
  geom_text(data=sig_test_summary,aes(x=2,y=run,label=sig_symbol),color='red',vjust=-1) +
  facet_wrap(~group,nrow=1)  +
  labs(x= 'Change in Perfomance Across Reaches (nse °C)',y= 'Holdout Experiment',fill = 'Model') +
  theme_bw() +
  theme(legend.position = 'top')

ggsave('../drb_gwnet/2_analysis/figures/Overall_Performance_Change_Segs.png',width = 6.5,height=3.5, units = 'in')
```

## Look at training times, etc

```{r}
finetune_logs <- view_train_longs('../river-dl/results/baseline/GWN') %>%
  mutate(model = 'GWN') %>%
  bind_rows(view_train_longs('../river-dl/results/baseline/RGCN') %>%
              mutate(model='RGCN')) %>%
  filter(run=='full_train')

training_times <- finetune_logs %>%group_by(model) %>%
  summarise(time = median(time),
            inf_time = median(val_time,na.rm=T))

epochs <- finetune_logs %>%group_by(model, run) %>%
  summarise(epochs = max(epoch)) %>%
  group_by(model) %>%
  summarise(Epochs = mean(epochs))

ggplot(finetune_logs, aes(x=epoch)) +
  geom_line(aes(y=loss, color = 'Loss', group=run), alpha = .3) +
  geom_line(aes(y=val_loss, color = "Val Loss", group = run), alpha = .3) +
  facet_wrap(~model)

### Trainable params rgcn=2681, gwn=373851
table <- tibble('model'='RGCN',"params"=2681, 'hyperparameters' = 6) %>%
  bind_rows(tibble('model'='GWN',"params"=373851, 'hyperparameters' = 11)) %>%
  left_join(training_times) %>%
  left_join(epochs) %>%
  select(model, time, inf_time, Epochs, params, hyperparameters) %>%
  mutate_if(is.numeric, ~round(.,1))

colors <- viridis::viridis(10, end = .7)
table %>%
  kableExtra::kbl(col.names = c("Model","Training Time\nper Epoch", "Inference Time\nper Epoch", "Mean Epochs \npre Early Stopping", 'Learnable\nParameters','Hyperparameters')) %>%
  #kableExtra::add_header_above(c('Overall RMSE by Temperature Bin' = 4)) %>%
  kableExtra::row_spec(1, color = "white", background = colors[1]) %>%
  kableExtra::row_spec(2, color = 'white', background = colors[10]) %>%
  kableExtra::kable_styling()


```

